apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-mysql-data
  labels:
    app: sonar-mysql-data
  annotations:
    volume.beta.kubernetes.io/storage-class: "ebs"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
