apiVersion: v1
kind: Service
metadata:
  name: sonar
spec:
  ports:
  - name: "sonar"
    port: 9001
    targetPort: 9000
  - name: "mysql"
    port: 3036
    targetPort: 3036
  selector:
    app: sonar
  type: ClusterIP
