apiVersion: v1
kind: ConfigMap
metadata:
  name: sonar-env
data:
  LDAP_BIND_DN: cn=admin,dc=ldap,dc=example,dc=com
  LDAP_BIND_PASSWORD: ###LDAP_MANAGER_PASSWORD### 
  LDAP_GROUP_BASE_DN: ou=groups,dc=ldap,dc=example,dc=com
  LDAP_GROUP_ID_ATTRIBUTE: cn
  LDAP_GROUP_REQUEST: (&(objectClass=groupOfUniqueNames)(uniqueMember={dn}))
  LDAP_URL: ldap://ldap:389
  LDAP_USER_BASE_DN: ou=people,dc=ldap,dc=example,dc=com
  LDAP_USER_EMAIL_ATTRIBUTE: mail
  LDAP_USER_REAL_NAME_ATTRIBUTE: displayName
  LDAP_USER_REQUEST: (&(objectClass=inetOrgPerson)(uid={login}))
  MYSQL_DATABASE: sonar
  MYSQL_PASSWORD: sonar
  MYSQL_ROOT_PASSWORD: sonar
  MYSQL_USER: sonar
  SONARQUBE_JDBC_PASSWORD: sonar
  SONARQUBE_JDBC_URL: jdbc:mysql://localhost:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
  SONARQUBE_JDBC_USERNAME: sonar
  dependency: container:sonar-mysql
