apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: sonar
  labels:
    app: sonar
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sonar
    spec:
      containers:
        - name: sonar-sql
          image: mysql:5.6.25
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: sonar-mysql-data
              mountPath: /var/lib/mysql
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                key: MYSQL_ROOT_PASSWORD
                name: sonar-env
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                key: MYSQL_USER
                name: sonar-env
          - name: MYSQL_PASSWORD
            valueFrom:
              configMapKeyRef:
                key: MYSQL_PASSWORD
                name: sonar-env
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                key: MYSQL_DATABASE
                name: sonar-env
        - name: sonar
          image: accenture/adop-sonar:0.3.5
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: sonar-data
              mountPath: /opt/sonarqube/data
            - name: sonar-extensions
              mountPath: /opt/sonarqube/extensions
            - name: sonar-logs
              mountPath: /opt/sonarqube/logs
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                key: MYSQL_ROOT_PASSWORD
                name: sonar-env
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                key: MYSQL_USER
                name: sonar-env
          - name: MYSQL_PASSWORD
            valueFrom:
              configMapKeyRef:
                key: MYSQL_PASSWORD
                name: sonar-env
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                key: MYSQL_DATABASE
                name: sonar-env
          - name: SONARQUBE_JDBC_USERNAME
            valueFrom:
              configMapKeyRef:
                key: SONARQUBE_JDBC_USERNAME
                name: sonar-env
          - name: SONARQUBE_JDBC_URL
            valueFrom:
              configMapKeyRef:
                key: SONARQUBE_JDBC_URL
                name: sonar-env
          - name: LDAP_URL
            valueFrom:
              configMapKeyRef:
                key: LDAP_URL
                name: sonar-env
          - name: LDAP_BIND_DN
            valueFrom:
              configMapKeyRef:
                key: LDAP_BIND_DN
                name: sonar-env
          - name: LDAP_BIND_PASSWORD
            valueFrom:
              configMapKeyRef:
                key: LDAP_BIND_PASSWORD
                name: sonar-env
          - name: LDAP_USER_BASE_DN
            valueFrom:
              configMapKeyRef:
                key: LDAP_USER_BASE_DN
                name: sonar-env
          - name: LDAP_USER_REQUEST
            valueFrom:
              configMapKeyRef:
                key: LDAP_USER_REQUEST
                name: sonar-env
          - name: LDAP_USER_REAL_NAME_ATTRIBUTE
            valueFrom:
              configMapKeyRef:
                key: LDAP_USER_REAL_NAME_ATTRIBUTE
                name: sonar-env
          - name: LDAP_USER_EMAIL_ATTRIBUTE
            valueFrom:
              configMapKeyRef:
                key: LDAP_USER_EMAIL_ATTRIBUTE
                name: sonar-env
          - name: LDAP_GROUP_BASE_DN
            valueFrom:
              configMapKeyRef:
                key: LDAP_GROUP_BASE_DN
                name: sonar-env
          - name: LDAP_GROUP_REQUEST
            valueFrom:
              configMapKeyRef:
                key: LDAP_GROUP_REQUEST
                name: sonar-env
          - name: LDAP_GROUP_ID_ATTRIBUTE
            valueFrom:
              configMapKeyRef:
                key: LDAP_GROUP_ID_ATTRIBUTE
                name: sonar-env
      volumes:
      - name: sonar-mysql-data
        persistentVolumeClaim:
          claimName: sonar-mysql-data
      - name: sonar-data
        persistentVolumeClaim:
           claimName: sonar-data
      - name: sonar-extensions
        emptyDir: {}
      - name: sonar-logs
        emptyDir: {}
